src/Entity/Answer.php
<?php

namespace App\Entity;

use Symfony\Component\Serializer\Annotation\Groups;
use App\Repository\AnswerRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiResource;

#[ORM\Entity(repositoryClass: AnswerRepository::class)]
#[ApiResource]
class Answer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['answer_read'])]
    private ?string $answer = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['answer_read'])]
    private ?int $score = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $publication_date = null;

    #[ORM\ManyToOne(inversedBy: 'answers')]
    private ?Question $question_id = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['answer_read'])]
    private ?int $prefered = null;

    #[ORM\ManyToOne]
    #[Groups(['answer_read'])]
    private ?Member $author_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAnswer(): ?string
    {
        return $this->answer;
    }

    public function setAnswer(?string $answer): static
    {
        $this->answer = $answer;

        return $this;
    }

    public function getScore(): ?int
    {
        return $this->score;
    }

    public function setScore(?int $score): static
    {
        $this->score = $score;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(?\DateTimeInterface $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getQuestionId(): ?Question
    {
        return $this->question_id;
    }

    public function setQuestionId(?Question $question_id): static
    {
        $this->question_id = $question_id;

        return $this;
    }

    public function getPrefered(): ?int
    {
        return $this->prefered;
    }

    public function setPrefered(?int $prefered): static
    {
        $this->prefered = $prefered;

        return $this;
    }

    public function getAuthorId(): ?Member
    {
        return $this->author_id;
    }

    public function setAuthorId(?Member $author_id): static
    {
        $this->author_id = $author_id;

        return $this;
    }
}

src/Form/AnswerType.php
<?php

namespace App\Form;

use App\Entity\Answer;
use App\Entity\Member;
use App\Entity\Question;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnswerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('answer')
            ->add('score')
            ->add('publication_date')
            ->add('prefered')
            ->add('question_id', EntityType::class, [
                'class' => Question::class,
'choice_label' => 'id',
            ])
            ->add('author_id', EntityType::class, [
                'class' => Member::class,
'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Answer::class,
        ]);
    }
}

src/Controller/AnswerController.php
<?php

namespace App\Controller;

use App\Entity\Answer;
use App\Form\AnswerType;
use App\Repository\AnswerRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/answer')]
class AnswerController extends AbstractController
{
    #[Route('/', name: 'app_answer_index', methods: ['GET'])]
    public function index(AnswerRepository $answerRepository): Response
    {
        return $this->render('answer/index.html.twig', [
            'answers' => $answerRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_answer_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $answer = new Answer();
        $form = $this->createForm(AnswerType::class, $answer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($answer);
            $entityManager->flush();

            return $this->redirectToRoute('app_answer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('answer/new.html.twig', [
            'answer' => $answer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_answer_show', methods: ['GET'])]
    public function show(Answer $answer): Response
    {
        return $this->render('answer/show.html.twig', [
            'answer' => $answer,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_answer_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Answer $answer, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AnswerType::class, $answer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_answer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('answer/edit.html.twig', [
            'answer' => $answer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_answer_delete', methods: ['POST'])]
    public function delete(Request $request, Answer $answer, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$answer->getId(), $request->request->get('_token'))) {
            $entityManager->remove($answer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_answer_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/api/AnswerController.php
<?php

namespace App\api\Controller;

use App\Entity\Answer;
use App\Form\AnswerType;
use App\Repository\AnswerRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;

#[Route('api/answer')]
class AnswerController extends AbstractController
{
    #[Route('/', name: 'app_answer_index', methods: ['GET'])]
    public function index(AnswerRepository $answerRepository): Response
    {
        return $this->render('answer/index.html.twig', [
            'answers' => $answerRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_answer_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $answer = new Answer();
        $form = $this->createForm(AnswerType::class, $answer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($answer);
            $entityManager->flush();

            return $this->redirectToRoute('app_answer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('answer/new.html.twig', [
            'answer' => $answer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_answer_show', methods: ['GET'])]
    public function show(Answer $answer, SerializerInterface $serializer): Response
    {
        // Sérialiser l'objet Answer en utilisant le groupe 'answer_read'
        $jsonContent = $serializer->serialize($answer, 'json', ['groups' => 'answer_read']);
        
        // Retourner la réponse JSON
        return new Response($jsonContent, 200, [
            'Content-Type' => 'application/json'
        ]);
        return $this->render('answer/show.html.twig', [
            'answer' => $answer,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_answer_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Answer $answer, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AnswerType::class, $answer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_answer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('answer/edit.html.twig', [
            'answer' => $answer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_answer_delete', methods: ['POST'])]
    public function delete(Request $request, Answer $answer, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $answer->getId(), $request->request->get('_token'))) {
            $entityManager->remove($answer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_answer_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/answer/_delete_form.html.twig
<form method="post" action="{{ path('app_answer_delete', {'id': answer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ answer.id) }}">
    <button class="btn">Delete</button>
</form>

templates/answer/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/answer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Answer{% endblock %}

{% block body %}
    <h1>Edit Answer</h1>

    {{ include('answer/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_answer_index') }}">back to list</a>

    {{ include('answer/_delete_form.html.twig') }}
{% endblock %}

templates/answer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Answer index{% endblock %}

{% block body %}
    <h1>Answer index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Answer</th>
                <th>Score</th>
                <th>Publication_date</th>
                <th>Prefered</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for answer in answers %}
            <tr>
                <td>{{ answer.id }}</td>
                <td>{{ answer.answer }}</td>
                <td>{{ answer.score }}</td>
                <td>{{ answer.publicationDate ? answer.publicationDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ answer.prefered }}</td>
                <td>
                    <a href="{{ path('app_answer_show', {'id': answer.id}) }}">show</a>
                    <a href="{{ path('app_answer_edit', {'id': answer.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_answer_new') }}">Create new</a>
{% endblock %}

templates/answer/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Answer{% endblock %}

{% block body %}
    <h1>Create new Answer</h1>

    {{ include('answer/_form.html.twig') }}

    <a href="{{ path('app_answer_index') }}">back to list</a>
{% endblock %}

templates/answer/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Answer{% endblock %}

{% block body %}
    <h1>Answer</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ answer.id }}</td>
            </tr>
            <tr>
                <th>Answer</th>
                <td>{{ answer.answer }}</td>
            </tr>
            <tr>
                <th>Score</th>
                <td>{{ answer.score }}</td>
            </tr>
            <tr>
                <th>Publication_date</th>
                <td>{{ answer.publicationDate ? answer.publicationDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Prefered</th>
                <td>{{ answer.prefered }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_answer_index') }}">back to list</a>

    <a href="{{ path('app_answer_edit', {'id': answer.id}) }}">edit</a>

    {{ include('answer/_delete_form.html.twig') }}
{% endblock %}