src/Entity/Member.php
<?php

namespace App\Entity;

use App\Repository\MemberRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MemberRepository::class)]
#[ORM\Table(name: '`member`')]
class Member
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $registration_date = null;

    #[ORM\Column(length: 255)]
    private ?string $biography = null;

    #[ORM\Column(nullable: true)]
    private ?int $reputation = null;

    #[ORM\Column(length: 255)]
    private ?string $country = null;

    #[ORM\Column(nullable: true)]
    private ?int $valideted = null;

    #[ORM\OneToMany(targetEntity: User::class, mappedBy: 'member_id')]
    private Collection $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRegistrationDate(): ?\DateTimeInterface
    {
        return $this->registration_date;
    }

    public function setRegistrationDate(\DateTimeInterface $registration_date): static
    {
        $this->registration_date = $registration_date;

        return $this;
    }

    public function getBiography(): ?string
    {
        return $this->biography;
    }

    public function setBiography(string $biography): static
    {
        $this->biography = $biography;

        return $this;
    }

    public function getReputation(): ?int
    {
        return $this->reputation;
    }

    public function setReputation(?int $reputation): static
    {
        $this->reputation = $reputation;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getValideted(): ?int
    {
        return $this->valideted;
    }

    public function setValideted(?int $valideted): static
    {
        $this->valideted = $valideted;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->setMemberId($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getMemberId() === $this) {
                $user->setMemberId(null);
            }
        }

        return $this;
    }
}

src/Form/MemberType.php
<?php

namespace App\Form;

use App\Entity\Member;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MemberType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('registration_date')
            ->add('biography')
            ->add('reputation')
            ->add('country')
            ->add('valideted')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Member::class,
        ]);
    }
}

src/Controller/MemberController.php
<?php

namespace App\Controller;

use App\Entity\Member;
use App\Form\MemberType;
use App\Repository\MemberRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/member')]
class MemberController extends AbstractController
{
    #[Route('/', name: 'app_member_index', methods: ['GET'])]
    public function index(MemberRepository $memberRepository): Response
    {
        return $this->render('member/index.html.twig', [
            'members' => $memberRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_member_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $member = new Member();
        $form = $this->createForm(MemberType::class, $member);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($member);
            $entityManager->flush();

            return $this->redirectToRoute('app_member_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('member/new.html.twig', [
            'member' => $member,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_member_show', methods: ['GET'])]
    public function show(Member $member): Response
    {
        return $this->render('member/show.html.twig', [
            'member' => $member,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_member_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Member $member, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MemberType::class, $member);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_member_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('member/edit.html.twig', [
            'member' => $member,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_member_delete', methods: ['POST'])]
    public function delete(Request $request, Member $member, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$member->getId(), $request->request->get('_token'))) {
            $entityManager->remove($member);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_member_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/member/_delete_form.html.twig
<form method="post" action="{{ path('app_member_delete', {'id': member.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ member.id) }}">
    <button class="btn">Delete</button>
</form>

templates/member/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/member/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Member{% endblock %}

{% block body %}
    <h1>Edit Member</h1>

    {{ include('member/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_member_index') }}">back to list</a>

    {{ include('member/_delete_form.html.twig') }}
{% endblock %}

templates/member/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Member index{% endblock %}

{% block body %}
    <h1>Member index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Registration_date</th>
                <th>Biography</th>
                <th>Reputation</th>
                <th>Country</th>
                <th>Valideted</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for member in members %}
            <tr>
                <td>{{ member.id }}</td>
                <td>{{ member.registrationDate ? member.registrationDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ member.biography }}</td>
                <td>{{ member.reputation }}</td>
                <td>{{ member.country }}</td>
                <td>{{ member.valideted }}</td>
                <td>
                    <a href="{{ path('app_member_show', {'id': member.id}) }}">show</a>
                    <a href="{{ path('app_member_edit', {'id': member.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_member_new') }}">Create new</a>
{% endblock %}

templates/member/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Member{% endblock %}

{% block body %}
    <h1>Create new Member</h1>

    {{ include('member/_form.html.twig') }}

    <a href="{{ path('app_member_index') }}">back to list</a>
{% endblock %}

templates/member/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Member{% endblock %}

{% block body %}
    <h1>Member</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ member.id }}</td>
            </tr>
            <tr>
                <th>Registration_date</th>
                <td>{{ member.registrationDate ? member.registrationDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Biography</th>
                <td>{{ member.biography }}</td>
            </tr>
            <tr>
                <th>Reputation</th>
                <td>{{ member.reputation }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ member.country }}</td>
            </tr>
            <tr>
                <th>Valideted</th>
                <td>{{ member.valideted }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_member_index') }}">back to list</a>

    <a href="{{ path('app_member_edit', {'id': member.id}) }}">edit</a>

    {{ include('member/_delete_form.html.twig') }}
{% endblock %}